engines:
   eslint:
     enabled: true
ratings:
   paths: ["**.js"]
exclude_paths:
  - .git/
  - node_modules/
  - coverage/
  - test/
  - examples/
  - karma.conf.js
checks:
  method-complexity:
    config:
      threshold: 6